version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - 0.0.0.0:5601:5601
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: http://192.168.1.5:9200
